// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/19/2026, 5:41:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/maa/Desktop/JF/compareEx/excel-comparison/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/plugins/**/*.{js,ts,mjs}","/Users/maa/Desktop/JF/compareEx/excel-comparison/composables/**/*.{js,ts,mjs}","/Users/maa/Desktop/JF/compareEx/excel-comparison/utils/**/*.{js,ts,mjs}","/Users/maa/Desktop/JF/compareEx/excel-comparison/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maa/Desktop/JF/compareEx/excel-comparison/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;